install:
	# Change all below from nautilus to caja
	mkdir -p ~/.local/share/caja-python/extensions/caja-copy-path
	cp caja-copy-path.py ~/.local/share/caja-python/extensions
	cp caja_copy_path.py translation.py ~/.local/share/caja-python/extensions/caja-copy-path
	cp -R translations ~/.local/share/caja-python/extensions/caja-copy-path/translations

uninstall:
	rm ~/.local/share/caja-python/extensions/caja-copy-path.py
	rm -rf ~/.local/share/caja-python/extensions/caja-copy-path
